<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <VersionPrefix>1.0.0</VersionPrefix>
    <Authors>Wiesław Šoltés</Authors>
    <Company>Wiesław Šoltés</Company>
    <Copyright>Copyright © Wiesław Šoltés</Copyright>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/wieslawsoltes/DisposableGenerator</RepositoryUrl>
  </PropertyGroup>
</Project>

