namespace DisposableGenerator;

internal static class AttributeSource
{
    internal const string Text = """
// <auto-generated />
#nullable enable
namespace DisposableGenerator
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class GenerateDisposableAttribute : global::System.Attribute
    {
        /// <summary>
        /// Gets or sets whether the type implements <see cref="global::System.IDisposable" />.
        /// </summary>
        public bool GenerateSynchronousDispose { get; set; } = true;

        /// <summary>
        /// Gets or sets whether the type also implements <c>IAsyncDisposable</c>.
        /// </summary>
        public bool GenerateAsyncDispose { get; set; }

        /// <summary>
        /// Gets or sets whether the generated disposal paths invoke <c>DisposeUnmanaged()</c>.
        /// </summary>
        public bool GenerateUnmanagedCleanup { get; set; }

        /// <summary>
        /// Gets or sets whether the generator emits a finalizer. This also enables unmanaged cleanup.
        /// </summary>
        public bool GenerateFinalizer { get; set; }
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class GeneratedDisposableAttribute : global::System.Attribute
    {
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class DisposeMemberAttribute : global::System.Attribute
    {
        /// <summary>
        /// Gets or sets the disposal priority. Lower values are disposed first; members with the same value use the configured declaration order.
        /// </summary>
        public int Order { get; set; }
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class BorrowedMemberAttribute : global::System.Attribute
    {
    }
}
""";
}
