using Microsoft.CodeAnalysis;

namespace DisposableGenerator;

internal static class DiagnosticDescriptors
{
    private const string Category = "DisposableGenerator";

    internal static readonly DiagnosticDescriptor TypeMustBePartial = new(
        "DISP001",
        "Generated disposable type must be partial",
        "Type '{0}' and all of its containing types must be declared partial",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor MemberRequiresGeneratedType = new(
        "DISP002",
        "Owned member requires a generated disposable type",
        "Member '{0}' is marked [DisposeMember], but its containing type is not marked [GenerateDisposable]",
        Category,
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor MemberMustBeDisposable = new(
        "DISP003",
        "Owned member must be disposable",
        "Member '{0}' is marked [DisposeMember], but its type '{1}' implements neither System.IDisposable nor System.IAsyncDisposable",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor UnsupportedDisposableBase = new(
        "DISP004",
        "Disposable base type is unsupported",
        "Type '{0}' has an IDisposable base type that is not generated by DisposableGenerator",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Generating a second disposal entry point could bypass or conflict with the base type's ownership contract.");

    internal static readonly DiagnosticDescriptor ManualDisposeImplementation = new(
        "DISP005",
        "Do not implement the disposal pattern manually",
        "Type '{0}' is marked [GenerateDisposable] and must not declare generated disposal entry points or core methods",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor UnownedDisposableMember = new(
        "DISP006",
        "Disposable member has no explicit ownership annotation",
        "Member '{0}' is disposable but is marked with neither [DisposeMember] nor [BorrowedMember]",
        Category,
        DiagnosticSeverity.Info,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor UnsupportedType = new(
        "DISP007",
        "Generated disposable type is unsupported",
        "Type '{0}' must be a non-static, non-record class",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Record equality and with-expression cloning are incompatible with hidden mutable lifetime state and unique resource ownership.");

    internal static readonly DiagnosticDescriptor InvalidOwnedMember = new(
        "DISP008",
        "Owned member is unsupported",
        "Member '{0}' must be a readable instance field or property",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor InvalidConfiguration = new(
        "DISP009",
        "Invalid DisposableGenerator configuration",
        "MSBuild property '{0}' has invalid value '{1}'; using '{2}'",
        Category,
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor ConflictingOwnership = new(
        "DISP010",
        "Disposable member has conflicting ownership",
        "Member '{0}' cannot be marked with both [DisposeMember] and [BorrowedMember]",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor FileLocalTypeUnsupported = new(
        "DISP011",
        "File-local generated disposable type is unsupported",
        "Type '{0}' or one of its containing types is file-local and cannot be augmented from a generated source file",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor GeneratedMemberCollision = new(
        "DISP012",
        "Member conflicts with generated disposal infrastructure",
        "Member '{0}' on type '{1}' conflicts with a member required by DisposableGenerator",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor BorrowedMemberRequiresGeneratedType = new(
        "DISP013",
        "Borrowed member requires a generated disposable type",
        "Member '{0}' is marked [BorrowedMember], but its containing type is not marked [GenerateDisposable]",
        Category,
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor InvalidBorrowedMember = new(
        "DISP014",
        "Borrowed member is unsupported",
        "Member '{0}' marked [BorrowedMember] must be a readable instance field or property whose type implements System.IDisposable or System.IAsyncDisposable",
        Category,
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor InvalidDisposalHook = new(
        "DISP015",
        "Disposal hook conflicts with generated hook",
        "Member '{0}' on type '{1}' must be an implementation-only 'partial void {0}()' method",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor UnsupportedBaseDisposeHook = new(
        "DISP016",
        "Base disposal member is unsupported",
        "Type '{0}' has an accessible Dispose() or Dispose(bool) base member that is not generated by DisposableGenerator",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Generating another disposal entry point or hook could hide or bypass the base type's cleanup contract.");

    internal static readonly DiagnosticDescriptor FinalizerUnsupported = new(
        "DISP017",
        "Handwritten finalizers conflict with generated disposal",
        "Type '{0}' declares a handwritten finalizer; use GenerateFinalizer so finalization shares the generated lifetime state",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor MutableOwnedMember = new(
        "DISP018",
        "Mutable owned member can leak a replaced resource",
        "Owned member '{0}' is mutable; DisposableGenerator disposes only the value held when the owner is disposed",
        Category,
        DiagnosticSeverity.Info,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor AsyncDisposeUnavailable = new(
        "DISP019",
        "IAsyncDisposable is unavailable",
        "Type '{0}' enables asynchronous disposal, but System.IAsyncDisposable is not available in this compilation",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor AsyncMemberRequiresAsyncGeneration = new(
        "DISP020",
        "Asynchronous ownership requires asynchronous disposal generation",
        "Member '{0}' implements only System.IAsyncDisposable; enable GenerateAsyncDispose on type '{1}'",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor AsyncGenerationMismatch = new(
        "DISP021",
        "Generated disposal hierarchy has inconsistent disposal modes",
        "Type '{0}' and its generated base type must use the same synchronous and asynchronous generation settings",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor AsyncOnlyMemberSkippedBySyncDispose = new(
        "DISP022",
        "Synchronous disposal cannot release an async-only member",
        "Member '{0}' implements only System.IAsyncDisposable and is released only by DisposeAsync(), not Dispose()",
        Category,
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor UnsupportedAsyncDisposableBase = new(
        "DISP023",
        "Asynchronously disposable base type is unsupported",
        "Type '{0}' has an IAsyncDisposable base type that is not generated by DisposableGenerator",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Generating a second asynchronous disposal entry point could bypass or conflict with the base type's ownership contract.");

    internal static readonly DiagnosticDescriptor InvalidUnmanagedCleanupHook = new(
        "DISP024",
        "Unmanaged cleanup hook conflicts with generated hook",
        "Member '{0}' on type '{1}' must be an implementation-only 'partial void DisposeUnmanaged()' method",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor InvalidGenerationMode = new(
        "DISP025",
        "Disposable generation mode is invalid",
        "Type '{0}' must generate at least one disposal interface, and finalization requires synchronous disposal generation",
        Category,
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);
}
