using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace DisposableGenerator;

internal static class SourceEmitter
{
    internal static string Emit(DisposableTypeModel model)
    {
        var builder = new StringBuilder();
        var indent = 0;

        Line(builder, indent, "// <auto-generated />");
        Line(builder, indent, "#nullable enable");

        if (!model.Type.ContainingNamespace.IsGlobalNamespace)
        {
            Line(builder, indent, "namespace " + SymbolHelpers.NamespaceName(model.Type.ContainingNamespace));
            Line(builder, indent, "{");
            indent++;
        }

        foreach (var containingType in SymbolHelpers.ContainingTypesOuterFirst(model.Type))
        {
            Line(builder, indent, SymbolHelpers.PartialDeclarationPrefix(containingType) + " " + SymbolHelpers.TypeDeclarationName(containingType));
            Line(builder, indent, "{");
            indent++;
        }

        var interfaceClause = model.HasGeneratedBase ? string.Empty : InterfaceClause(model);
        Line(builder, indent, SymbolHelpers.PartialDeclarationPrefix(model.Type) + " " + SymbolHelpers.TypeDeclarationName(model.Type) + interfaceClause);
        Line(builder, indent, "{");
        indent++;

        EmitBody(builder, indent, model);

        indent--;
        Line(builder, indent, "}");

        foreach (var _ in SymbolHelpers.ContainingTypesOuterFirst(model.Type))
        {
            indent--;
            Line(builder, indent, "}");
        }

        if (!model.Type.ContainingNamespace.IsGlobalNamespace)
        {
            indent--;
            Line(builder, indent, "}");
        }

        return builder.ToString();
    }

    private static void EmitBody(StringBuilder builder, int indent, DisposableTypeModel model)
    {
        Line(builder, indent, "private int __DisposableGenerator_disposeState;");
        if (model.GenerateUnmanagedCleanup && model.GenerateSynchronousDispose)
        {
            Line(builder, indent, "private int __DisposableGenerator_unmanagedDisposeState;");
        }

        if (!model.HasGeneratedBase && model.GenerateSynchronousDispose && model.GenerateAsyncDispose)
        {
            Line(builder, indent, "private int __DisposableGenerator_asyncCleanupCompleted;");
        }

        if (!model.HasGeneratedBase && model.Options.GenerateRegistrationMethod)
        {
            Line(builder, indent, "private readonly object __DisposableGenerator_disposeGate = new object();");
            Line(builder, indent, "private global::System.Collections.Generic.List<object>? __DisposableGenerator_registeredDisposables;");
        }

        Line(builder, indent);

        if (!model.HasGeneratedBase)
        {
            if (model.GenerateSynchronousDispose)
            {
                EmitPublicDispose(builder, indent);
                Line(builder, indent);
            }

            if (model.GenerateAsyncDispose)
            {
                EmitPublicDisposeAsync(builder, indent, model);
                Line(builder, indent);
            }

            if (model.Options.GenerateRegistrationMethod)
            {
                EmitRegistrationMethod(builder, indent, model.Type, model.Options);
                Line(builder, indent);
                if (model.GenerateAsyncDispose)
                {
                    EmitAsyncRegistrationMethod(builder, indent, model.Type, model.Options);
                    Line(builder, indent);
                }
            }
        }

        if (model.GenerateSynchronousDispose)
        {
            EmitDisposeBoolean(builder, indent, model);
        }

        if (model.GenerateAsyncDispose)
        {
            Line(builder, indent);
            EmitDisposeAsyncCore(builder, indent, model);
        }

        if (model.Options.GenerateDisposalHooks)
        {
            Line(builder, indent);
            Line(builder, indent, "partial void OnDisposing();");
            Line(builder, indent);
            Line(builder, indent, "partial void OnDisposed();");
        }

        if (model.GenerateUnmanagedCleanup)
        {
            Line(builder, indent);
            Line(builder, indent, "partial void DisposeUnmanaged();");
        }

        if (model.GenerateFinalizer)
        {
            Line(builder, indent);
            EmitFinalizer(builder, indent, model.Type);
        }
    }

    private static string InterfaceClause(DisposableTypeModel model)
    {
        if (model.GenerateSynchronousDispose && model.GenerateAsyncDispose)
        {
            return " : global::System.IDisposable, global::System.IAsyncDisposable";
        }

        return model.GenerateSynchronousDispose
            ? " : global::System.IDisposable"
            : " : global::System.IAsyncDisposable";
    }

    private static void EmitPublicDispose(StringBuilder builder, int indent)
    {
        Line(builder, indent, "/// <inheritdoc />");
        Line(builder, indent, "public void Dispose()");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "Dispose(true);");
        Line(builder, indent + 1, "global::System.GC.SuppressFinalize(this);");
        Line(builder, indent, "}");
    }

    private static void EmitPublicDisposeAsync(StringBuilder builder, int indent, DisposableTypeModel model)
    {
        Line(builder, indent, "/// <inheritdoc />");
        Line(builder, indent, "public async global::System.Threading.Tasks.ValueTask DisposeAsync()");
        Line(builder, indent, "{");
        if (model.GenerateSynchronousDispose &&
            model.Options.DisposalExceptionBehavior == DisposalExceptionBehavior.ContinueAndAggregate)
        {
            Line(builder, indent + 1, "global::System.Collections.Generic.List<global::System.Exception>? __exceptions = null;");
            EmitAggregateAction(builder, indent + 1, "await DisposeAsyncCore().ConfigureAwait(false);", "__exceptions");
            EmitAggregateAction(
                builder,
                indent + 1,
                "if (global::System.Threading.Volatile.Read(ref __DisposableGenerator_asyncCleanupCompleted) != 0) { Dispose(false); }",
                "__exceptions");
            EmitAggregateThrow(builder, indent + 1, "__exceptions");
        }
        else if (model.GenerateSynchronousDispose)
        {
            Line(builder, indent + 1, "try");
            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "await DisposeAsyncCore().ConfigureAwait(false);");
            Line(builder, indent + 1, "}");
            Line(builder, indent + 1, "finally");
            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "if (global::System.Threading.Volatile.Read(ref __DisposableGenerator_asyncCleanupCompleted) != 0)");
            Line(builder, indent + 2, "{");
            Line(builder, indent + 3, "Dispose(false);");
            Line(builder, indent + 2, "}");
            Line(builder, indent + 1, "}");
        }
        else
        {
            Line(builder, indent + 1, "await DisposeAsyncCore().ConfigureAwait(false);");
        }

        Line(builder, indent + 1, "global::System.GC.SuppressFinalize(this);");
        Line(builder, indent, "}");
    }

    private static void EmitRegistrationMethod(StringBuilder builder, int indent, INamedTypeSymbol type, GeneratorOptions options)
    {
        var access = type.IsSealed ? "private" : "protected";
        var typeParameter = SymbolHelpers.RegistrationTypeParameterName(type);
        Line(builder, indent, "/// <summary>Registers a dynamically owned disposable and returns the same instance.</summary>");
        Line(builder, indent, "/// <typeparam name=\"" + typeParameter + "\">The disposable type.</typeparam>");
        Line(builder, indent, "/// <param name=\"disposable\">The resource whose lifetime is owned by this instance.</param>");
        Line(builder, indent, "/// <returns><paramref name=\"disposable\" />.</returns>");
        Line(builder, indent, access + " " + typeParameter + " " + options.RegistrationMethodName + "<" + typeParameter + ">(" + typeParameter + " disposable)");
        Line(builder, indent, "    where " + typeParameter + " : global::System.IDisposable");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "if (global::System.Object.ReferenceEquals(disposable, null))");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, "throw new global::System.ArgumentNullException(nameof(disposable));");
        Line(builder, indent + 1, "}");
        Line(builder, indent);
        Line(builder, indent + 1, "lock (__DisposableGenerator_disposeGate)");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, "if (__DisposableGenerator_disposeState == 0)");
        Line(builder, indent + 2, "{");
        Line(builder, indent + 3, "if (__DisposableGenerator_registeredDisposables is null)");
        Line(builder, indent + 3, "{");
        Line(builder, indent + 4, "__DisposableGenerator_registeredDisposables = new global::System.Collections.Generic.List<object>();");
        Line(builder, indent + 3, "}");
        Line(builder, indent);
        Line(builder, indent + 3, "__DisposableGenerator_registeredDisposables.Add(disposable);");
        Line(builder, indent + 3, "return disposable;");
        Line(builder, indent + 2, "}");
        Line(builder, indent + 1, "}");
        Line(builder, indent);

        if (options.PostDisposeRegistrationBehavior == PostDisposeRegistrationBehavior.Throw)
        {
            Line(builder, indent + 1, "throw new global::System.ObjectDisposedException(this.GetType().FullName);");
        }
        else
        {
            Line(builder, indent + 1, "disposable.Dispose();");
            Line(builder, indent + 1, "return disposable;");
        }

        Line(builder, indent, "}");
    }

    private static void EmitAsyncRegistrationMethod(StringBuilder builder, int indent, INamedTypeSymbol type, GeneratorOptions options)
    {
        var access = type.IsSealed ? "private" : "protected";
        var typeParameter = SymbolHelpers.RegistrationTypeParameterName(type);
        var asyncModifier = options.PostDisposeRegistrationBehavior == PostDisposeRegistrationBehavior.DisposeImmediately
            ? "async "
            : string.Empty;
        Line(builder, indent, "/// <summary>Registers a dynamically owned asynchronous disposable and returns the same instance.</summary>");
        Line(builder, indent, "/// <typeparam name=\"" + typeParameter + "\">The asynchronous disposable type.</typeparam>");
        Line(builder, indent, "/// <param name=\"disposable\">The resource whose lifetime is owned by this instance.</param>");
        Line(builder, indent, "/// <returns>An operation whose result is <paramref name=\"disposable\" />.</returns>");
        Line(builder, indent, access + " " + asyncModifier + "global::System.Threading.Tasks.ValueTask<" + typeParameter + "> " + options.AsyncRegistrationMethodName + "<" + typeParameter + ">(" + typeParameter + " disposable)");
        Line(builder, indent, "    where " + typeParameter + " : global::System.IAsyncDisposable");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "if (global::System.Object.ReferenceEquals(disposable, null))");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, "throw new global::System.ArgumentNullException(nameof(disposable));");
        Line(builder, indent + 1, "}");
        Line(builder, indent);
        Line(builder, indent + 1, "lock (__DisposableGenerator_disposeGate)");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, "if (__DisposableGenerator_disposeState == 0)");
        Line(builder, indent + 2, "{");
        Line(builder, indent + 3, "if (__DisposableGenerator_registeredDisposables is null)");
        Line(builder, indent + 3, "{");
        Line(builder, indent + 4, "__DisposableGenerator_registeredDisposables = new global::System.Collections.Generic.List<object>();");
        Line(builder, indent + 3, "}");
        Line(builder, indent);
        Line(builder, indent + 3, "__DisposableGenerator_registeredDisposables.Add(disposable);");
        if (options.PostDisposeRegistrationBehavior == PostDisposeRegistrationBehavior.Throw)
        {
            Line(builder, indent + 3, "return new global::System.Threading.Tasks.ValueTask<" + typeParameter + ">(disposable);");
        }
        else
        {
            Line(builder, indent + 3, "return disposable;");
        }

        Line(builder, indent + 2, "}");
        Line(builder, indent + 1, "}");
        Line(builder, indent);

        if (options.PostDisposeRegistrationBehavior == PostDisposeRegistrationBehavior.Throw)
        {
            Line(builder, indent + 1, "throw new global::System.ObjectDisposedException(this.GetType().FullName);");
        }
        else
        {
            Line(builder, indent + 1, "await disposable.DisposeAsync().ConfigureAwait(false);");
            Line(builder, indent + 1, "return disposable;");
        }

        Line(builder, indent, "}");
    }

    private static void EmitDisposeBoolean(StringBuilder builder, int indent, DisposableTypeModel model)
    {
        if (model.Options.DisposalExceptionBehavior == DisposalExceptionBehavior.ContinueAndAggregate)
        {
            EmitAggregateDisposeBoolean(builder, indent, model);
            return;
        }

        if (model.HasGeneratedBase)
        {
            EmitDisposeBooleanDocumentation(builder, indent);
            Line(builder, indent, "protected override void Dispose(bool disposing)");
            Line(builder, indent, "{");
            EmitFinalizationPath(builder, indent + 1, model);
            Line(builder, indent + 1, "if (global::System.Threading.Interlocked.Exchange(ref __DisposableGenerator_disposeState, 1) != 0)");
            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "return;");
            Line(builder, indent + 1, "}");
            Line(builder, indent);
            Line(builder, indent + 1, "try");
            Line(builder, indent + 1, "{");
            EmitSynchronousLevelCleanup(builder, indent + 2, model, registeredVariable: null);
            Line(builder, indent + 1, "}");
            Line(builder, indent + 1, "finally");
            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "base.Dispose(disposing);");
            Line(builder, indent + 1, "}");
            Line(builder, indent, "}");
            return;
        }

        var access = model.Type.IsSealed ? "private" : "protected virtual";
        EmitDisposeBooleanDocumentation(builder, indent);
        Line(builder, indent, access + " void Dispose(bool disposing)");
        Line(builder, indent, "{");
        EmitFinalizationPath(builder, indent + 1, model);

        if (model.Options.GenerateRegistrationMethod)
        {
            Line(builder, indent + 1, "object[]? __registered = null;");
            Line(builder, indent + 1, "lock (__DisposableGenerator_disposeGate)");
            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "if (__DisposableGenerator_disposeState != 0)");
            Line(builder, indent + 2, "{");
            Line(builder, indent + 3, "return;");
            Line(builder, indent + 2, "}");
            Line(builder, indent);
            Line(builder, indent + 2, "__DisposableGenerator_disposeState = 1;");
            Line(builder, indent + 2, "if (disposing && __DisposableGenerator_registeredDisposables is not null)");
            Line(builder, indent + 2, "{");
            Line(builder, indent + 3, "__registered = __DisposableGenerator_registeredDisposables.ToArray();");
            Line(builder, indent + 2, "}");
            Line(builder, indent);
            Line(builder, indent + 2, "__DisposableGenerator_registeredDisposables = null;");
            Line(builder, indent + 1, "}");
            Line(builder, indent);
            EmitSynchronousLevelCleanup(builder, indent + 1, model, "__registered");
        }
        else
        {
            Line(builder, indent + 1, "if (global::System.Threading.Interlocked.Exchange(ref __DisposableGenerator_disposeState, 1) != 0)");
            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "return;");
            Line(builder, indent + 1, "}");
            Line(builder, indent);
            EmitSynchronousLevelCleanup(builder, indent + 1, model, registeredVariable: null);
        }

        Line(builder, indent, "}");
    }

    private static void EmitFinalizationPath(StringBuilder builder, int indent, DisposableTypeModel model)
    {
        Line(builder, indent, "if (!disposing)");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "global::System.Threading.Interlocked.Exchange(ref __DisposableGenerator_disposeState, 1);");
        if (model.HasGeneratedBase)
        {
            Line(builder, indent + 1, "try");
            Line(builder, indent + 1, "{");
            EmitUnmanagedCleanupOnce(builder, indent + 2, model);
            Line(builder, indent + 1, "}");
            Line(builder, indent + 1, "finally");
            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "base.Dispose(false);");
            Line(builder, indent + 1, "}");
        }
        else
        {
            EmitUnmanagedCleanupOnce(builder, indent + 1, model);
        }

        Line(builder, indent + 1, "return;");
        Line(builder, indent, "}");
        Line(builder, indent);
    }

    private static void EmitUnmanagedCleanupOnce(StringBuilder builder, int indent, DisposableTypeModel model)
    {
        if (!model.GenerateUnmanagedCleanup)
        {
            return;
        }

        Line(builder, indent, "if (global::System.Threading.Interlocked.Exchange(ref __DisposableGenerator_unmanagedDisposeState, 1) == 0)");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "DisposeUnmanaged();");
        Line(builder, indent, "}");
    }

    private static void EmitSynchronousLevelCleanup(
        StringBuilder builder,
        int indent,
        DisposableTypeModel model,
        string? registeredVariable)
    {
        if (!model.GenerateUnmanagedCleanup)
        {
            EmitManagedCleanup(builder, indent, model, registeredVariable);
            return;
        }

        Line(builder, indent, "try");
        Line(builder, indent, "{");
        EmitManagedCleanup(builder, indent + 1, model, registeredVariable);
        Line(builder, indent, "}");
        Line(builder, indent, "finally");
        Line(builder, indent, "{");
        EmitUnmanagedCleanupOnce(builder, indent + 1, model);
        Line(builder, indent, "}");
    }

    private static void EmitManagedCleanup(StringBuilder builder, int indent, DisposableTypeModel model, string? registeredVariable)
    {
        Line(builder, indent, "if (!disposing)");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "return;");
        Line(builder, indent, "}");

        if (model.Options.GenerateDisposalHooks)
        {
            Line(builder, indent);
            Line(builder, indent, "OnDisposing();");
        }

        for (var index = 0; index < model.Members.Count; index++)
        {
            var ownedMember = model.Members[index];
            if (!ownedMember.SupportsSynchronousDispose)
            {
                continue;
            }

            var member = ownedMember.Symbol;
            Line(builder, indent, "((global::System.IDisposable?)this." + SymbolHelpers.EscapeIdentifier(member.Name) + ")?.Dispose();");
        }

        if (registeredVariable is not null)
        {
            Line(builder, indent, "if (" + registeredVariable + " is not null)");
            Line(builder, indent, "{");
            if (model.Options.RegisteredResourceDisposalOrder == RegisteredResourceDisposalOrder.ReverseRegistration)
            {
                Line(builder, indent + 1, "for (var __index = " + registeredVariable + ".Length - 1; __index >= 0; __index--)");
            }
            else
            {
                Line(builder, indent + 1, "for (var __index = 0; __index < " + registeredVariable + ".Length; __index++)");
            }

            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "if (" + registeredVariable + "[__index] is global::System.IDisposable __disposable)");
            Line(builder, indent + 2, "{");
            Line(builder, indent + 3, "__disposable.Dispose();");
            Line(builder, indent + 2, "}");
            Line(builder, indent + 1, "}");
            Line(builder, indent, "}");
        }

        if (model.Options.GenerateDisposalHooks)
        {
            Line(builder, indent);
            Line(builder, indent, "OnDisposed();");
        }
    }

    private static void EmitAggregateDisposeBoolean(StringBuilder builder, int indent, DisposableTypeModel model)
    {
        if (model.HasGeneratedBase)
        {
            EmitDisposeBooleanDocumentation(builder, indent);
            Line(builder, indent, "protected override void Dispose(bool disposing)");
            Line(builder, indent, "{");
            EmitAggregateFinalizationPath(builder, indent + 1, model);
            Line(builder, indent + 1, "if (global::System.Threading.Interlocked.Exchange(ref __DisposableGenerator_disposeState, 1) != 0)");
            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "return;");
            Line(builder, indent + 1, "}");
            Line(builder, indent);
            Line(builder, indent + 1, "global::System.Collections.Generic.List<global::System.Exception>? __exceptions = null;");
            Line(builder, indent + 1, "if (disposing)");
            Line(builder, indent + 1, "{");
            EmitAggregateManagedCleanup(builder, indent + 2, model, registeredVariable: null);
            Line(builder, indent + 1, "}");
            Line(builder, indent);
            if (model.GenerateUnmanagedCleanup)
            {
                EmitAggregateUnmanagedCleanupOnce(builder, indent + 1, "__exceptions");
            }

            EmitAggregateAction(builder, indent + 1, "base.Dispose(disposing);", "__exceptions");
            EmitAggregateThrow(builder, indent + 1, "__exceptions");
            Line(builder, indent, "}");
            return;
        }

        var access = model.Type.IsSealed ? "private" : "protected virtual";
        EmitDisposeBooleanDocumentation(builder, indent);
        Line(builder, indent, access + " void Dispose(bool disposing)");
        Line(builder, indent, "{");
        EmitAggregateFinalizationPath(builder, indent + 1, model);

        if (model.Options.GenerateRegistrationMethod)
        {
            Line(builder, indent + 1, "object[]? __registered = null;");
            Line(builder, indent + 1, "lock (__DisposableGenerator_disposeGate)");
            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "if (__DisposableGenerator_disposeState != 0)");
            Line(builder, indent + 2, "{");
            Line(builder, indent + 3, "return;");
            Line(builder, indent + 2, "}");
            Line(builder, indent);
            Line(builder, indent + 2, "__DisposableGenerator_disposeState = 1;");
            Line(builder, indent + 2, "if (disposing && __DisposableGenerator_registeredDisposables is not null)");
            Line(builder, indent + 2, "{");
            Line(builder, indent + 3, "__registered = __DisposableGenerator_registeredDisposables.ToArray();");
            Line(builder, indent + 2, "}");
            Line(builder, indent);
            Line(builder, indent + 2, "__DisposableGenerator_registeredDisposables = null;");
            Line(builder, indent + 1, "}");
        }
        else
        {
            Line(builder, indent + 1, "if (global::System.Threading.Interlocked.Exchange(ref __DisposableGenerator_disposeState, 1) != 0)");
            Line(builder, indent + 1, "{");
            Line(builder, indent + 2, "return;");
            Line(builder, indent + 1, "}");
        }

        Line(builder, indent);
        Line(builder, indent + 1, "global::System.Collections.Generic.List<global::System.Exception>? __exceptions = null;");
        Line(builder, indent + 1, "if (disposing)");
        Line(builder, indent + 1, "{");
        EmitAggregateManagedCleanup(
            builder,
            indent + 2,
            model,
            model.Options.GenerateRegistrationMethod ? "__registered" : null);
        Line(builder, indent + 1, "}");
        if (model.GenerateUnmanagedCleanup)
        {
            Line(builder, indent);
            EmitAggregateUnmanagedCleanupOnce(builder, indent + 1, "__exceptions");
        }

        EmitAggregateThrow(builder, indent + 1, "__exceptions");
        Line(builder, indent, "}");
    }

    private static void EmitAggregateFinalizationPath(StringBuilder builder, int indent, DisposableTypeModel model)
    {
        Line(builder, indent, "if (!disposing)");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "global::System.Threading.Interlocked.Exchange(ref __DisposableGenerator_disposeState, 1);");
        Line(builder, indent + 1, "global::System.Collections.Generic.List<global::System.Exception>? __finalizationExceptions = null;");
        if (model.GenerateUnmanagedCleanup)
        {
            EmitAggregateUnmanagedCleanupOnce(builder, indent + 1, "__finalizationExceptions");
        }

        if (model.HasGeneratedBase)
        {
            EmitAggregateAction(builder, indent + 1, "base.Dispose(false);", "__finalizationExceptions");
        }

        EmitAggregateThrow(builder, indent + 1, "__finalizationExceptions");
        Line(builder, indent + 1, "return;");
        Line(builder, indent, "}");
        Line(builder, indent);
    }

    private static void EmitAggregateUnmanagedCleanupOnce(StringBuilder builder, int indent, string exceptionsVariable) =>
        EmitAggregateAction(
            builder,
            indent,
            "if (global::System.Threading.Interlocked.Exchange(ref __DisposableGenerator_unmanagedDisposeState, 1) == 0) { DisposeUnmanaged(); }",
            exceptionsVariable);

    private static void EmitAggregateManagedCleanup(
        StringBuilder builder,
        int indent,
        DisposableTypeModel model,
        string? registeredVariable)
    {
        if (model.Options.GenerateDisposalHooks)
        {
            EmitAggregateAction(builder, indent, "OnDisposing();", "__exceptions");
        }

        foreach (var ownedMember in model.Members)
        {
            if (!ownedMember.SupportsSynchronousDispose)
            {
                continue;
            }

            var memberName = SymbolHelpers.EscapeIdentifier(ownedMember.Symbol.Name);
            EmitAggregateAction(
                builder,
                indent,
                "((global::System.IDisposable?)this." + memberName + ")?.Dispose();",
                "__exceptions");
        }

        if (registeredVariable is not null)
        {
            Line(builder, indent, "if (" + registeredVariable + " is not null)");
            Line(builder, indent, "{");
            if (model.Options.RegisteredResourceDisposalOrder == RegisteredResourceDisposalOrder.ReverseRegistration)
            {
                Line(builder, indent + 1, "for (var __index = " + registeredVariable + ".Length - 1; __index >= 0; __index--)");
            }
            else
            {
                Line(builder, indent + 1, "for (var __index = 0; __index < " + registeredVariable + ".Length; __index++)");
            }

            Line(builder, indent + 1, "{");
            EmitAggregateAction(
                builder,
                indent + 2,
                "if (" + registeredVariable + "[__index] is global::System.IDisposable __disposable) { __disposable.Dispose(); }",
                "__exceptions");
            Line(builder, indent + 1, "}");
            Line(builder, indent, "}");
        }

        if (model.Options.GenerateDisposalHooks)
        {
            EmitAggregateAction(builder, indent, "OnDisposed();", "__exceptions");
        }
    }

    private static void EmitAggregateAction(StringBuilder builder, int indent, string statement, string exceptionsVariable)
    {
        Line(builder, indent, "try");
        Line(builder, indent, "{");
        Line(builder, indent + 1, statement);
        Line(builder, indent, "}");
        Line(builder, indent, "catch (global::System.AggregateException __exception)");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "if (" + exceptionsVariable + " is null)");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, exceptionsVariable + " = new global::System.Collections.Generic.List<global::System.Exception>();");
        Line(builder, indent + 1, "}");
        Line(builder, indent);
        Line(builder, indent + 1, exceptionsVariable + ".AddRange(__exception.Flatten().InnerExceptions);");
        Line(builder, indent, "}");
        Line(builder, indent, "catch (global::System.Exception __exception)");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "if (" + exceptionsVariable + " is null)");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, exceptionsVariable + " = new global::System.Collections.Generic.List<global::System.Exception>();");
        Line(builder, indent + 1, "}");
        Line(builder, indent);
        Line(builder, indent + 1, exceptionsVariable + ".Add(__exception);");
        Line(builder, indent, "}");
    }

    private static void EmitAggregateThrow(StringBuilder builder, int indent, string exceptionsVariable)
    {
        Line(builder, indent, "if (" + exceptionsVariable + " is not null)");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "throw new global::System.AggregateException(" + exceptionsVariable + ");");
        Line(builder, indent, "}");
    }

    private static void EmitDisposeAsyncCore(StringBuilder builder, int indent, DisposableTypeModel model)
    {
        if (model.Options.DisposalExceptionBehavior == DisposalExceptionBehavior.ContinueAndAggregate)
        {
            EmitAggregateDisposeAsyncCore(builder, indent, model);
            return;
        }

        var access = model.HasGeneratedBase
            ? "protected override"
            : model.Type.IsSealed ? "private" : "protected virtual";
        EmitDisposeAsyncCoreDocumentation(builder, indent);
        Line(builder, indent, access + " async global::System.Threading.Tasks.ValueTask DisposeAsyncCore()");
        Line(builder, indent, "{");
        var registeredVariable = PrepareAsyncDisposal(builder, indent + 1, model);
        Line(builder, indent);
        Line(builder, indent + 1, "try");
        Line(builder, indent + 1, "{");
        EmitAsyncManagedCleanup(builder, indent + 2, model, registeredVariable, aggregate: false);
        Line(builder, indent + 1, "}");
        Line(builder, indent + 1, "finally");
        Line(builder, indent + 1, "{");
        if (model.GenerateUnmanagedCleanup && !model.GenerateSynchronousDispose)
        {
            if (model.HasGeneratedBase)
            {
                Line(builder, indent + 2, "try");
                Line(builder, indent + 2, "{");
                Line(builder, indent + 3, "DisposeUnmanaged();");
                Line(builder, indent + 2, "}");
                Line(builder, indent + 2, "finally");
                Line(builder, indent + 2, "{");
                Line(builder, indent + 3, "await base.DisposeAsyncCore().ConfigureAwait(false);");
                Line(builder, indent + 2, "}");
            }
            else
            {
                Line(builder, indent + 2, "DisposeUnmanaged();");
            }
        }
        else if (model.HasGeneratedBase)
        {
            Line(builder, indent + 2, "await base.DisposeAsyncCore().ConfigureAwait(false);");
        }

        if (!model.HasGeneratedBase && model.GenerateSynchronousDispose)
        {
            Line(builder, indent + 2, "global::System.Threading.Volatile.Write(ref __DisposableGenerator_asyncCleanupCompleted, 1);");
        }

        Line(builder, indent + 1, "}");
        if (!HasAwaitedAsyncCleanup(model))
        {
            Line(builder, indent);
            Line(builder, indent + 1, "await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);");
        }

        Line(builder, indent, "}");
    }

    private static void EmitAggregateDisposeAsyncCore(StringBuilder builder, int indent, DisposableTypeModel model)
    {
        var access = model.HasGeneratedBase
            ? "protected override"
            : model.Type.IsSealed ? "private" : "protected virtual";
        EmitDisposeAsyncCoreDocumentation(builder, indent);
        Line(builder, indent, access + " async global::System.Threading.Tasks.ValueTask DisposeAsyncCore()");
        Line(builder, indent, "{");
        var registeredVariable = PrepareAsyncDisposal(builder, indent + 1, model);
        Line(builder, indent);
        Line(builder, indent + 1, "global::System.Collections.Generic.List<global::System.Exception>? __exceptions = null;");
        EmitAsyncManagedCleanup(builder, indent + 1, model, registeredVariable, aggregate: true);
        if (model.GenerateUnmanagedCleanup && !model.GenerateSynchronousDispose)
        {
            EmitAggregateAction(builder, indent + 1, "DisposeUnmanaged();", "__exceptions");
        }

        if (model.HasGeneratedBase)
        {
            EmitAggregateAction(
                builder,
                indent + 1,
                "await base.DisposeAsyncCore().ConfigureAwait(false);",
                "__exceptions");
        }

        if (!HasAwaitedAsyncCleanup(model))
        {
            Line(builder, indent + 1, "await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);");
        }

        if (!model.HasGeneratedBase && model.GenerateSynchronousDispose)
        {
            Line(builder, indent + 1, "global::System.Threading.Volatile.Write(ref __DisposableGenerator_asyncCleanupCompleted, 1);");
        }

        EmitAggregateThrow(builder, indent + 1, "__exceptions");
        Line(builder, indent, "}");
    }

    private static string? PrepareAsyncDisposal(StringBuilder builder, int indent, DisposableTypeModel model)
    {
        if (model.HasGeneratedBase || !model.Options.GenerateRegistrationMethod)
        {
            Line(builder, indent, "if (global::System.Threading.Interlocked.Exchange(ref __DisposableGenerator_disposeState, 1) != 0)");
            Line(builder, indent, "{");
            Line(builder, indent + 1, "return;");
            Line(builder, indent, "}");
            return null;
        }

        Line(builder, indent, "object[]? __registered = null;");
        Line(builder, indent, "lock (__DisposableGenerator_disposeGate)");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "if (__DisposableGenerator_disposeState != 0)");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, "return;");
        Line(builder, indent + 1, "}");
        Line(builder, indent);
        Line(builder, indent + 1, "__DisposableGenerator_disposeState = 1;");
        Line(builder, indent + 1, "if (__DisposableGenerator_registeredDisposables is not null)");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, "__registered = __DisposableGenerator_registeredDisposables.ToArray();");
        Line(builder, indent + 1, "}");
        Line(builder, indent);
        Line(builder, indent + 1, "__DisposableGenerator_registeredDisposables = null;");
        Line(builder, indent, "}");
        return "__registered";
    }

    private static void EmitAsyncManagedCleanup(
        StringBuilder builder,
        int indent,
        DisposableTypeModel model,
        string? registeredVariable,
        bool aggregate)
    {
        if (model.Options.GenerateDisposalHooks)
        {
            EmitMaybeAggregateAction(builder, indent, "OnDisposing();", aggregate);
        }

        for (var memberIndex = 0; memberIndex < model.Members.Count; memberIndex++)
        {
            var ownedMember = model.Members[memberIndex];
            var memberName = SymbolHelpers.EscapeIdentifier(ownedMember.Symbol.Name);
            var statement = ownedMember.SupportsAsynchronousDispose
                ? "if (this." + memberName + " is global::System.IAsyncDisposable __asyncMember" + memberIndex + ") " +
                  "{ await __asyncMember" + memberIndex + ".DisposeAsync().ConfigureAwait(false); }"
                : "((global::System.IDisposable?)this." + memberName + ")?.Dispose();";
            EmitMaybeAggregateAction(builder, indent, statement, aggregate);
        }

        if (registeredVariable is not null)
        {
            Line(builder, indent, "if (" + registeredVariable + " is not null)");
            Line(builder, indent, "{");
            if (model.Options.RegisteredResourceDisposalOrder == RegisteredResourceDisposalOrder.ReverseRegistration)
            {
                Line(builder, indent + 1, "for (var __index = " + registeredVariable + ".Length - 1; __index >= 0; __index--)");
            }
            else
            {
                Line(builder, indent + 1, "for (var __index = 0; __index < " + registeredVariable + ".Length; __index++)");
            }

            Line(builder, indent + 1, "{");
            var statement = "if (" + registeredVariable + "[__index] is global::System.IAsyncDisposable __asyncDisposable) " +
                "{ await __asyncDisposable.DisposeAsync().ConfigureAwait(false); } " +
                "else if (" + registeredVariable + "[__index] is global::System.IDisposable __disposable) { __disposable.Dispose(); }";
            EmitMaybeAggregateAction(builder, indent + 2, statement, aggregate);
            Line(builder, indent + 1, "}");
            Line(builder, indent, "}");
        }

        if (model.Options.GenerateDisposalHooks)
        {
            EmitMaybeAggregateAction(builder, indent, "OnDisposed();", aggregate);
        }
    }

    private static void EmitMaybeAggregateAction(StringBuilder builder, int indent, string statement, bool aggregate)
    {
        if (aggregate)
        {
            EmitAggregateAction(builder, indent, statement, "__exceptions");
        }
        else
        {
            Line(builder, indent, statement);
        }
    }

    private static bool HasAwaitedAsyncCleanup(DisposableTypeModel model) =>
        model.HasGeneratedBase ||
        (!model.HasGeneratedBase && model.Options.GenerateRegistrationMethod) ||
        model.Members.Any(member => member.SupportsAsynchronousDispose);

    private static void EmitFinalizer(StringBuilder builder, int indent, INamedTypeSymbol type)
    {
        Line(builder, indent, "/// <summary>Finalizes unmanaged resources if deterministic disposal was not performed.</summary>");
        Line(builder, indent, "~" + SymbolHelpers.EscapeIdentifier(type.Name) + "()");
        Line(builder, indent, "{");
        Line(builder, indent + 1, "try");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, "Dispose(false);");
        Line(builder, indent + 1, "}");
        Line(builder, indent + 1, "catch");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, "// Finalizers must not allow exceptions to escape.");
        Line(builder, indent + 1, "}");
        Line(builder, indent, "}");
    }

    private static void EmitDisposeBooleanDocumentation(StringBuilder builder, int indent)
    {
        Line(builder, indent, "/// <summary>Releases resources owned by this level of the inheritance hierarchy.</summary>");
        Line(builder, indent, "/// <param name=\"disposing\"><see langword=\"true\" /> to release managed resources.</param>");
    }

    private static void EmitDisposeAsyncCoreDocumentation(StringBuilder builder, int indent)
    {
        Line(builder, indent, "/// <summary>Asynchronously releases resources owned by this level of the inheritance hierarchy.</summary>");
        Line(builder, indent, "/// <returns>An operation representing asynchronous cleanup.</returns>");
    }

    private static void Line(StringBuilder builder, int indent, string text = "")
    {
        if (text.Length > 0)
        {
            builder.Append(' ', indent * 4);
            builder.Append(text);
        }

        builder.AppendLine();
    }
}
