<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework Condition="'$(IntegrationTargetFramework)' == ''">net10.0</TargetFramework>
    <TargetFramework Condition="'$(IntegrationTargetFramework)' != ''">$(IntegrationTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <DisposableGenerator_DisposalExceptionBehavior>ContinueAndAggregate</DisposableGenerator_DisposalExceptionBehavior>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DisposableGenerator" Version="$(DisposableGeneratorPackageVersion)" PrivateAssets="all" />
  </ItemGroup>
</Project>
